Repository DeveloperAcademy-POSTECH/2024-MacC-M15-45SeekDance, pull requests merged in 2025-04, with the labels that each got.

#196 [#195] Phase6 디자인 자잘한 수정
  StepSquad/StepSquad/Resource/Assets.xcassets/Down/Ultimate.imageset/Ultimate 1.png
  StepSquad/StepSquad/Resource/Assets.xcassets/Down/Ultimate.imageset/Ultimate 2.png
  StepSquad/StepSquad/Resource/Assets.xcassets/Down/Ultimate.imageset/Ultimate.png
  StepSquad/StepSquad/Resource/Assets.xcassets/StairImages/Ultimate.imageset/Contents.json
  StepSquad/StepSquad/Resource/Assets.xcassets/StairImages/Ultimate.imageset/Ultimate 1.png
  StepSquad/StepSquad/Resource/Assets.xcassets/StairImages/Ultimate.imageset/Ultimate 2.png
  StepSquad/StepSquad/Resource/Assets.xcassets/StairImages/Ultimate.imageset/Ultimate.png
  StepSquad/StepSquad/View/CustomTableView.swift
  StepSquad/StepSquad/View/DescendRecordView.swift
  StepSquad/StepSquad/View/MainViewPhase3.swift
  StepSquad/StepSquad/View/NewItemView.swift
Labels: fix, design

#199 [#197] 노티피케이션 뷰와 기능 구현 완료
  StepSquad/StepSquad/View/ExplainView.swift
  StepSquad/StepSquad/View/NotiView.swift
Labels: feature

#202 [#200] 하산하기 이후 메인뷰 리셋, 획득 재료 & 성취 리셋
  StepSquad/StepSquad/Helper/GameCenterManager.swift
  StepSquad/StepSquad/View/MainViewPhase3.swift
  StepSquad/StepSquad/View/ResetNavigationView.swift
Labels: fix
