Repository DeveloperAcademy-POSTECH/2024-MacC-M15-45SeekDance, pull requests merged in 2025-01, with the labels that each got.

#151 Feature/#150 그루가 참조 할 코드(메인 병합X)
  StepSquad/StepSquad.xcodeproj/project.pbxproj
  StepSquad/StepSquad/HealthKit.swift
  StepSquad/StepSquad/View/MainViewPhase3.swift
Labels: feature

#153 [#152] 저장소 저장 방식 통일해서 권한날짜 덮어씌어지지 않는 에러 핸들링
  StepSquad/StepSquad/HealthKit.swift
  StepSquad/StepSquad/View/EntryCertificateView.swift
Labels: fix

#155 [Fix]
  StepSquad/StepSquad/HealthKit.swift
  StepSquad/StepSquad/View/EntryCertificateView.swift
Labels: fix

#163 [Feat]하산하기 플로우 구현 중간 과정
  StepSquad/StepSquad/Resource/Assets.xcassets/Down/Contents.json
  StepSquad/StepSquad/Resource/Assets.xcassets/Down/Down1.imageset/Contents.json
  StepSquad/StepSquad/Resource/Assets.xcassets/Down/Down1.imageset/Donw1 1.png
  StepSquad/StepSquad/Resource/Assets.xcassets/Down/Down1.imageset/Donw1 2.png
  StepSquad/StepSquad/Resource/Assets.xcassets/Down/Down1.imageset/Donw1.png
  StepSquad/StepSquad/Resource/Assets.xcassets/Down/Down2.imageset/Contents.json
  StepSquad/StepSquad/Resource/Assets.xcassets/Down/Down2.imageset/Down2 1.png
  StepSquad/StepSquad/Resource/Assets.xcassets/Down/Down2.imageset/Down2 2.png
  StepSquad/StepSquad/Resource/Assets.xcassets/Down/Down2.imageset/Down2.png
  StepSquad/StepSquad/Resource/Assets.xcassets/Down/Down3.imageset/Contents.json
  StepSquad/StepSquad/Resource/Assets.xcassets/Down/Down3.imageset/Down3 1.png
  StepSquad/StepSquad/Resource/Assets.xcassets/Down/Down3.imageset/Down3 2.png
  StepSquad/StepSquad/Resource/Assets.xcassets/Down/Down3.imageset/Down3.png
  StepSquad/StepSquad/View/MainViewPhase3.swift
Labels: feature

#166 [Fix] 병합 충돌 해결
  StepSquad/StepSquad/View/MainViewPhase3.swift
Labels: fix

#173 [#169] feature: install RiveRuntime package and show example
  StepSquad/StepSquad.xcodeproj/project.pbxproj
  StepSquad/StepSquad.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  StepSquad/StepSquad/Resource/reset.riv
  StepSquad/StepSquad/View/RiveExampleView.swift
Labels: feature

#172 [Feat] 리셋 함수 연결된 버튼에 하산 기록 추가 함수 연결
  StepSquad/StepSquad/HealthKit.swift
  StepSquad/StepSquad/Resource/ResetLogs.swift
  StepSquad/StepSquad/View/CustomTableView.swift
  StepSquad/StepSquad/View/DescendRecordView.swift
  StepSquad/StepSquad/View/EntryCertificateView.swift
  StepSquad/StepSquad/View/MainViewPhase3.swift
Labels: feature

#177 [#176] 디자인 수정&리셋 프로세스 중에 보여줄 데이터
  StepSquad/StepSquad.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  StepSquad/StepSquad/Resource/Assets.xcassets/Down/Ultimate.imageset/Contents.json
  StepSquad/StepSquad/Resource/Assets.xcassets/Down/Ultimate.imageset/Ultimate 1.png
  StepSquad/StepSquad/Resource/Assets.xcassets/Down/Ultimate.imageset/Ultimate 2.png
  StepSquad/StepSquad/Resource/Assets.xcassets/Down/Ultimate.imageset/Ultimate.png
  StepSquad/StepSquad/Resource/ResetLogs.swift
  StepSquad/StepSquad/View/MainViewPhase3.swift
Labels: feature, design

#180 [#179] 데이터 파라미터 전달 및 입단증에 들어가는 배열 역순
  StepSquad/StepSquad.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  StepSquad/StepSquad/View/CustomTableView.swift
  StepSquad/StepSquad/View/MainViewPhase3.swift
Labels: feature

#182 [#181] feature: 오프라인 환경에서 게임센터 로그인이 되지 않은 경우 하산하기를 막기
  StepSquad/StepSquad/HealthKit.swift
  StepSquad/StepSquad/Helper/GameCenterManager.swift
  StepSquad/StepSquad/View/MainViewPhase3.swift
  StepSquad/StepSquad/View/ShowNewBirdView.swift
Labels: fix, feature
